version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: topu_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: topu_backend
      MYSQL_USER: topu_backend
      MYSQL_PASSWORD: topu_backend
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
